# Generated by Django 3.0.7 on 2020-06-12 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartcontroller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='smartcontroller.Node'),
        ),
    ]
