# Generated by Django 3.0.7 on 2020-06-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcontroller', '0002_auto_20200612_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
