# Generated by Django 3.0.7 on 2021-01-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcontroller', '0003_auto_20200613_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='mac',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
