# Generated by Django 3.0.7 on 2021-01-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcontroller', '0004_device_mac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('PI', 'Raspberry Pi'), ('PLUG', 'Smart Plug'), ('BULB', 'Smart Bulb'), ('LINUX', 'Linux'), ('PC', 'PC')], default='PLUG', max_length=5),
        ),
    ]
