# Generated by Django 3.0.7 on 2021-05-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcontroller', '0005_auto_20210107_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('PI', 'Raspberry Pi'), ('PLUG', 'Smart Plug'), ('BULB', 'Smart Bulb'), ('LINUX', 'Linux'), ('PC', 'PC'), ('ROKU', 'Roku'), ('AMZN', 'Amazon FireTv')], default='PLUG', max_length=5),
        ),
    ]
