# Generated by Django 3.2.7 on 2021-09-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcontroller', '0006_auto_20210526_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('key', models.CharField(max_length=50)),
            ],
        ),
    ]
