# Generated by Django 3.2.7 on 2021-09-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcontroller', '0007_clientkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientkey',
            name='ip',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
