# Generated by Django 3.2.7 on 2021-09-27 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcontroller', '0008_alter_clientkey_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientkey',
            name='key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
