# Generated by Django 3.2.7 on 2021-09-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcontroller', '0009_alter_clientkey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('PI', 'Raspberry Pi'), ('PLUG', 'Smart Plug'), ('BULB', 'Smart Bulb'), ('LINUX', 'Linux'), ('PC', 'PC'), ('ROKU', 'Roku'), ('AMZN', 'Amazon FireTv'), ('LGTV', 'LG Smart TV')], default='PLUG', max_length=5),
        ),
    ]
