# Generated by Django 3.2.7 on 2021-10-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcontroller', '0010_alter_device_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
