name: Build UI

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    home:
      description: 'location'
      required: false
      default: 'The Octoverse'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install Electron Builder
      run: npm install -g electron-builder

    - name: Install Dependancies
      run: npm install
      working-directory: ./electron-ui

    - name: Build Angular
      run: npm run build:prod
      working-directory: ./electron-ui

    - name: Build Electron
      run: electron-builder build --armv7l --linux
      working-directory: ./electron-ui

    - uses: papeloto/action-zip@v1
      with:
        files: electron-ui/release/ server update.sh uninstall.sh install.sh
        recursive: false
        dest: ./release/smartcontroller.zip
    
    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'release'
