name: NodeJS with Gulp

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependancies
      run: npm install
      working-directory: ./electron-ui
      
    - name: Build Angular
      run: npm run build:prod
      working-directory: ./electron-ui
      
    - name: Build Electron
      run: electron-builder build --armv7l --linux
      working-directory: ./electron-ui
