name: Build UI

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    home:
      description: 'location'
      required: false
      default: 'The Octoverse'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install Electron Builder
      run: npm install -g electron-builder

    - name: Install Dependancies
      run: npm install
      working-directory: ./electron-ui
      
    - name: Build Angular
      run: npm run build:prod
      working-directory: ./electron-ui
      
    - name: Build Electron
      run: electron-builder build --armv7l --linux
      working-directory: ./electron-ui

    - uses: papeloto/action-zip@v1
      with:
        files: ./electron-ui/release/
        dest: ./smartcontroller.zip
    
    - name: Deploy to S3
      uses: medlypharmacy/s3-artifacts-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws_s3_bucket_name: ${{ secrets.AWS_S3_BUCKET }}
        source_path: './smartcontroller.zip'
