name: Build UI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install Dependancies
      run: npm install -g electron-builder

    - name: Install Dependancies
      run: npm install
      working-directory: ./electron-ui
      
    - name: Build Angular
      run: npm run build:prod
      working-directory: ./electron-ui
      
    - name: Build Electron
      run: electron-builder build --armv7l --linux
      working-directory: ./electron-ui
